### ISSUE TITLE
webstart throws AccessControlException

### ISSUE THREAD

**Issue by yahman72** [robotframework/remoteswinglibrary#28]
RemoteSwingLib v2.0.3
RF v2.8.3
Win 8.1
JRE v1.8.0_60

When running the webstart tests I get an AccessControlException.
The test app starts but the test fails with `RemoteSwingLibraryTimeoutError: Agent port not received before timeout`

<pre>
==> remote_stdout_76203799-3b32-4851-ae84-13a9c398e89c.txt <==

==> remote_stderr_aa115107-859c-43c8-81c6-576e5d116afe.txt <==
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.awt")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPackageAccess(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.robotframework.remoteswinglibrary.agent.FindAppContextWithWindow.getAppContextWithWindow(FindAppContextWithWindow.java:53)
        at org.robotframework.remoteswinglibrary.agent.FindAppContextWithWindow.run(FindAppContextWithWindow.java:41)
        at java.lang.Thread.run(Unknown Source)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.awt")
Error starting remote server
Picked up JAVA_TOOL_OPTIONS: -javaagent:"C:\git\fork-rswing\remoteswinglibrary-2.0.3.jar"=127.0.0.1:54397:DEBUG
</pre>

It works if I run javaws with "grant all" policy i.e.

<pre>
            grant {
                permission java.security.AllPermission;
            };
</pre>

That is:
`Start Application    test-app    javaws -verbose -J-Djava.security.policy="c:\\tmp\\grant_all.policy" ${WEBSTART DIR}/test-app/test-application.jnlp    40`
instead of:
`Start Application    test-app    javaws -verbose ${WEBSTART DIR}/test-app/test-application.jnlp    40`

FYI:
Web Start "-verbose" output from the failing execution

<pre>
---------------------------
Java(TM) Web Start 11.60.2.27-fcs
---------------------------
Launching: C:\java\jre\v1.8.0_60\bin\javaw.exe
C:\java\jre\v1.8.0_60\bin\javaw.exe
 -classpath
 C:\java\jre\v1.8.0_60\lib\deploy.jar
 -Djava.security.policy=file:C:\java\jre\v1.8.0_60\lib\security\javaws.policy
 -DtrustProxy=true
 -Xverify:remote
 -Djnlpx.home=C:\java\jre\v1.8.0_60\bin
 -Djava.security.manager
 -Djnlpx.origFilenameArg=C:\git\fork-rswing\src\test\robotframework\acceptance/webstart/test-app/test-application.jnlp
 -Djnlpx.remove=true
 -Dsun.awt.warmup=true
 -Xbootclasspath/a:C:\java\jre\v1.8.0_60\lib\javaws.jar;C:\java\jre\v1.8.0_60\lib\deploy.jar;C:\java\jre\v1.8.0_60\lib\plugin.jar
 -Djnlpx.splashport=54415
 -Djnlpx.jvm=C:\java\jre\v1.8.0_60\bin\javaw.exe
 com.sun.javaws.Main
 -verbose
 -notWebJava
 C:\tmp\jari\javaws3
</pre>

**Comment by yahman72** [comment]
oops, just saw the latest commit. That seems to fix the issue.

Anyway, if somebody else has had the same issue - now it's at least documented :-)
It took a while to figure this out because I didn't find any documentation mentioning that a policy-file would have been needed for the webstart stuff.

**Comment by balak143** [comment]
I am also getting the same error on the latest as well..... I tried with grant all permission workaround also still i get this error though my application lauches but fails with the same error

**Comment by taciosd** [comment]
RemoteSwingLibrary v2.0.3
RobotFramework v2.9.2
Linux CentOS release 6.7 (Final)
JRE v1.8.0_73

I'm also experimenting this exception. The command I have in robotframework script is:
`Start Application   myapp   ${JAVAWS} ${URL}  30`
Which translates in execution time to:
`javaws http://dsv.ep.pet....com:8080/init`

In log we have:
```
Failed to start application: Traceback (most recent call last):
  File "/Work/y5kx/workspace/sgbdbloco/sgbdbloco-trunk/sgbdbloco-client/src/test/resources/robotframework/libraries/remoteswinglibrary-2.0.3.jar/RemoteSwingLibrary.py", line 295, in start_application
    self._application_started(alias, timeout=timeout, name_contains=name_contains, accept_old=False)
  File "/Work/y5kx/workspace/sgbdbloco/sgbdbloco-trunk/sgbdbloco-client/src/test/resources/robotframework/libraries/remoteswinglibrary-2.0.3.jar/RemoteSwingLibrary.py", line 321, in _application_started
    url = self._get_agent_address(name_contains, accept_old)
  File "/Work/y5kx/workspace/sgbdbloco/sgbdbloco-trunk/sgbdbloco-client/src/test/resources/robotframework/libraries/remoteswinglibrary-2.0.3.jar/RemoteSwingLibrary.py", line 342, in _get_agent_address
    raise RemoteSwingLibraryTimeoutError('Agent port not received before timeout')
RemoteSwingLibraryTimeoutError: Agent port not received before timeout

  16:02:17.944  INFO  Waiting for process to complete.
  16:02:17.945  INFO  Process completed.

STDERR: Picked up JAVA_TOOL_OPTIONS: -javaagent:"/workspace/trunk/app/src/test/resources/robotframework/libraries/remoteswinglibrary-2.0.3.jar"=127.0.0.1:28023:DEBUG
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.awt")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.robotframework.remoteswinglibrary.agent.FindAppContextWithWindow.getAppContextWithWindow(FindAppContextWithWindow.java:53)
        at org.robotframework.remoteswinglibrary.agent.FindAppContextWithWindow.run(FindAppContextWithWindow.java:41)
        at java.lang.Thread.run(Thread.java:745)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.awt")
Error starting remote server
  16:02:17.953  FAIL  RemoteSwingLibraryTimeoutError: Agent port not received before timeout
```

I already tried the policy override solution and it didn't work.
@balak143 @yahman72 Any progress with this issue?

**Comment by taciosd** [comment]
Nevermind, I downloaded the master version (2.0.4dev) and tested again. It worked.
Thank you!

**Comment by filipecduarte** [comment]
Hi @taciosd 
Can you tell me where i can get this compile version? 
The last released is 2.0.3.

Regards
Filipe Duarte

**Comment by taciosd** [comment]
Hi @filipecduarte 
You can get it from the master branch of the project

You can clone it using git
https://github.com/robotframework/remoteswinglibrary.git

Or download a zip file
https://github.com/robotframework/remoteswinglibrary/archive/master.zip

To create the Jar file use "mvn package" command on the root directory of the downloaded project.

**Comment by filipecduarte** [comment]
Thanks @taciosd 

Work fine.
