### ISSUE TITLE
Unable to import RemoteSwingLibrary with RIDE 1.4.1 using python 2.7.6

### ISSUE THREAD

**Issue by hishamakbar** [robotframework/remoteswinglibrary#29]
I have RIDE 1.4.1 installed using Python 2.7.6 with ws version 2.8.12.1.
I added the jar file location to PYTHONPATH.
I'm using windows 7.
The installation docs don't mentioned copying the files in a certain folder so I just kept them in Downloads for now.

When I import RemoteSwingLibrary in Ride, it stays red.
I am not entering any arguments for the import.

Log: 
```
20151012 13:37:54.568 [INFO]: Started RIDE 1.4.1 using python version 2.7.6 with wx version 2.8.12.1 in win32.

20151012 13:37:56.823 [WARN]: Importing test library "RemoteSwingLibrary" failed

Traceback (most recent call last):
Initializing test library 'RemoteSwingLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context
Traceback (most recent call last):
  File "C:\Users\hakbar\Downloads\RemoteSwingLibrary\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 216, in __init__
    self._create_env(bool(debug), port != 'TEST')
  File "C:\Users\hakbar\Downloads\RemoteSwingLibrary\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 242, in _create_env
    BuiltIn().set_global_variable('\${REMOTESWINGLIBRARYPATH}', self._escape_path(RemoteSwingLibrary.AGENT_PATH))
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 1130, in set_global_variable
    name = self._get_var_name(name)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 1138, in _get_var_name
    name = self._resolve_possible_variable(orig)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 1146, in _resolve_possible_variable
    resolved = self._variables[name]
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 2682, in _variables
    return self._namespace.variables
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 2674, in _namespace
    return self._context.namespace
  File "C:\Python27\lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py", line 2669, in _context
    raise RobotNotRunningError('Cannot access execution context')
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 45, in TestLibrary
    lib.create_handlers()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 102, in create_handlers
    self.handlers = self._create_handlers(self.get_instance())
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 163, in get_instance
    self._libinst = self._get_instance()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 173, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 227, in _raise_creating_instance_failed
    % (self.name, args_text, msg, details))
```

**Comment by javier-jimenez** [comment]
I had this same problem, solved it by adding "C:\Python27\lib\*" (that asterisk * in the end made the difference). You can add this quickly in RIDE -> Preferences -> Importing -> Pythonpath field just type: C:\Python27\lib* and make sure the jar file is inside C:\Python27\lib folder. Hope this helps

**Comment by hishamakbar** [comment]
That didn't make a difference. I still see the same Error log.

**Comment by mikaheikkinen** [comment]
Were you able to solve this one? I have same problem and wondering if you found solution?

**Comment by hishamakbar** [comment]
Hi. No I wasn't able to solve this yet. I'm not getting a chance to dig deeper into this. Please let me know if you can figure something out.

**Comment by pekkaklarck** [comment]
This seems to be caused by the lib calling `BuiltIn().set_global_variable` in its `__init__`. That requires Robot to be executing tests which obviously isn't the case when RIDE tries to import it. I haven't looked at the code to see could this be easily avoided.

**Comment by WojtekKowaluk** [comment]
Do you think wrapping BuildIn calls with try-except statement is proper solution for this?

**Comment by yanne** [comment]
It seems that the `_create_env` -method which fails, already takes an argument `robot_running` argument which is not (and have to ever been) used. I am not sure what would be the best way to determine this, perhaps a simple try-expect would be enough. Any thoughts, @pekkaklarck ?

**Comment by pekkaklarck** [comment]
Yeah, something like this ought to work:

```python

try:
    from robot.libraries.BuiltIn import RobotNotRunningError
except ImportError:  # Support RF < 2.8.5
    RobotNotRunningError = AttributeError

try:
    BuiltIn().set_global_variable(...)
except RobotNotRunningError:
    # ...
```

**Comment by WojtekKowaluk** [comment]
Oh, thanks for mentioning that thing for compatibility with older version. I would most likely miss that.

**Comment by hishamakbar** [comment]
I downloaded the files again and tried to import but it still didn't work. Can anyone confirm that the issue went away?

**Comment by WojtekKowaluk** [comment]
No new version were released yet. I think we will release one today.

**Comment by WojtekKowaluk** [comment]
It is out now: https://github.com/robotframework/remoteswinglibrary/releases/tag/2.1.0
