### ISSUE TITLE
Initializing test library 'RemoteSwingLibrary' with no arguments failed

### ISSUE THREAD

**Issue by hleskien** [robotframework/remoteswinglibrary#83]
Hi,

something between 2.2.3 and 2.2.4 has changed, so that the library import can't have no parameters:

[ ERROR ] Error in file 'C:\Develop\repos\[...].robot': Initializing test library 'RemoteSwingLibrary' with no arguments failed: AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "__pyclasspath__/RemoteSwingLibrary.py", line 270, in __init__
  File "__pyclasspath__/RemoteSwingLibrary.py", line 289, in _initiate
  File "__pyclasspath__/RemoteSwingLibrary.py", line 289, in _initiate
  File "__pyclasspath__/RemoteSwingLibrary.py", line 343, in _escape_path

Kind regards

Holger

**Comment by mihaiparvu** [comment]
I can't seem to reproduce this problem. Can you give me a bit more information on how you're using the library and your environment, an example test that is failing and how do you run it?

**Comment by hleskien** [comment]
Sure. In short I'm using Maven 3.6.0 with Robot Framework Maven Plugin 1.5.1. I'll put together an example which fails.

**Comment by hleskien** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.leskien</groupId>
    <artifactId>remoteswinglibrary_issue83</artifactId>
    <version>1</version>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.robotframework</groupId>
            <artifactId>remoteswinglibrary</artifactId>
            <version>2.2.4</version>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>integration-test</defaultGoal>

        <plugins>
            <plugin>
                <groupId>org.robotframework</groupId>
                <artifactId>robotframework-maven-plugin</artifactId>
                <version>1.5.1</version>
                <executions>
                    <execution>
                        <id>robotframework</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <testCasesDirectory>${project.basedir}</testCasesDirectory>
                            <extraPathDirectories/>
                            <variables/>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>
`

`*** Settings ***
Library        RemoteSwingLibrary

*** Test Cases ***
Demo
    Application Started    jspy    timeout=10s    remote_port=12345    remote_host=127.0.0.1
`

**Comment by hleskien** [comment]
@rticau: closed without comment?

**Comment by rticau** [comment]
Thanks @hleskien for feedback. Is this issue still valid for you?

**Comment by hleskien** [comment]
Maybe. Please give me 24h for testing the latest release.

**Comment by hleskien** [comment]
I'd like to reopen this. It still happens on my (Windows) machine. Same example but with remoteswinglibrary 2.2.8, robotframework-maven-plugin 1.7.2 and Java 1.8.0_281.

**Comment by rticau** [comment]
@hleskien  appreciate your time to reproduce it. Your workaround is to use an older version?

**Comment by hleskien** [comment]
Yes, I'm still using 2.2.3. However, this is becoming increasingly difficult due to Javalib-Core conflicts.

**Comment by cristii006** [comment]
Hello @hleskien,

Thanks for your example you provided and for the time spend on testing different versions of RSL. Unfortunately I did not manage to reproduce this issue.  I would like you to ask you: how do you start your java application and if there is something peculiar about the way you are starting it(some settings, running options, etc.)?. Also is any reason for choosing that port or is just as an example?

Best regards,
Cristi

**Comment by rticau** [comment]
@hleskien  Hi! Could you provide the info requested above by @cristii006 ?

**Comment by hleskien** [comment]
Sorry, I forgot. Will do ASAP.

**Comment by hleskien** [comment]
> Thanks for your example you provided and for the time spend on testing different versions of RSL. Unfortunately I did not manage to reproduce this issue. I would like you to ask you: how do you start your java application and if there is something peculiar about the way you are starting it(some settings, running options, etc.)?. Also is any reason for choosing that port or is just as an example?

Sorry it took me so long!

The Java Application is not started at all. But when I start it with `java -jar` it makes no difference.
The Port is just an example. As I wrote before, when I try the same with RemoteSwingLibrary 2.2.3 everything works as expected.

Environment for my test today:
- Windows 10 64-bit
- jdk-8u281-windows-x64
- apache-maven-3.6.3
- robotframework-maven-plugin 1.7.2
- remoteswinglibrary 2.2.8

Output:
```
...
[ WARN ] Failed to auto-detect Java version. Assuming Java is older than 9. To run in newer Javacompatibility mode set java9_or_newer=True when importing the library.
[ ERROR ] Error in file 'C:\Develop\repos\tau\robot\suite\rsl_bugreport\Issue83.robot' on line 2: Initializing test library 'RemoteSwingLibrary' with no arguments failed: AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "__pyclasspath__/RemoteSwingLibrary.py", line 270, in __init__
    self._initiate(port, debug, java9_or_newer)
  File "__pyclasspath__/RemoteSwingLibrary.py", line 284, in _initiate
    BuiltIn().set_global_variable('\${REMOTESWINGLIBRARYPATH}',
  File "__pyclasspath__/RemoteSwingLibrary.py", line 284, in _initiate
    BuiltIn().set_global_variable('\${REMOTESWINGLIBRARYPATH}',
  File "__pyclasspath__/RemoteSwingLibrary.py", line 340, in _escape_path
    return text.replace("\\", "\\\\")
Rsl Bugreport.Issue83
==============================================================================
Demo                                                                  | FAIL |
No keyword with name 'Application Started' found.
```

Kind regards

Holger

**Comment by mihaiparvu** [comment]
@hleskien if you add remoteswinglibrary.jar to `PYTHONPATH` in your system's environment variables it should work.

**Comment by mihaiparvu** [comment]
Closing due to no activity for a while. @hleskien if you have any updates feel free to share.

**Comment by hleskien** [comment]
Yes, thanks. Unfortunately, I am no longer in a position to run further tests or investigate the problem.
