### ISSUE TITLE
What ever i tried, It is not working, application started but you can't get it

### ISSUE THREAD

**Issue by mel-exerp** [robotframework/remoteswinglibrary#84]
File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 433, in start_application self._application_started(alias, timeout, name_contains, remote_port, accept_old=False) File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 481, in _application_started url = self._get_agent_address(name_contains, accept_old)
File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 502, in _get_agent_address raise RemoteSwingLibraryTimeoutError('Agent port not received before timeout') RemoteSwingLibraryTimeoutError: Agent port not received before timeout

**Comment by mel-exerp** [comment]
| Failed to start application: Traceback (most recent call last):   

File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 433, in start_application     self._application_started(alias, timeout, name_contains, remote_port, accept_old=False)   File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 481, in _application_started     url = self._get_agent_address(name_contains, accept_old)   
File "xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 502, in _get_agent_address     raise RemoteSwingLibraryTimeoutError('Agent port not received before timeout') RemoteSwingLibraryTimeoutError: Agent port not received before timeout

-- | --

**Comment by mel-exerp** [comment]
So it is successfully started then try to listed to the port then it couldn't find it!!!!
What is wrong with this library!!
I am using windows, robotframework-3.1.2.jar , latest version of RemoteSwingLibrary, java 8
Python 3, jython2.7.0      and I am using standalone version of robotframework because the others are not working at all !!

Any help

**Comment by a9038889** [comment]
I have a similar problem
